import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Pie } from 'react-chartjs-2';
import {
  Chart as ChartJS,
  ArcElement,
  Tooltip,
  Legend
} from 'chart.js';
import jsPDF from 'jspdf';
import { FaTrophy, FaDownload, FaHome, FaChartPie, FaFileAlt } from 'react-icons/fa';
import {
  DEEP_SPACE_BLUE,
  CORPORATE_NAVY,
  CYBER_TEAL,
  LUMINOUS_ACCENT,
  LIGHT_SLATE,
  MID_SLATE,
  VIBRANT_GREEN,
  CHART_SKY_BLUE,
  CHART_PINK,
  CHART_PURPLE
} from '../../constants';

ChartJS.register(ArcElement, Tooltip, Legend);

const CapstoneSummary = ({ userData, investorProfile, ipsText, onComplete, isCompleted }) => {
  const navigate = useNavigate();
  const [isDownloading, setIsDownloading] = useState(false);

  // Get portfolio allocation based on investor profile
  const getPortfolioAllocation = (profile) => {
    const allocations = {
      Conservative: { stocks: 20, bonds: 70, cash: 10 },
      Moderate: { stocks: 55, bonds: 35, cash: 10 },
      Aggressive: { stocks: 80, bonds: 15, cash: 5 }
    };
    return allocations[profile] || allocations.Moderate;
  };

  const allocation = getPortfolioAllocation(investorProfile);

  const chartData = {
    labels: ['Stocks', 'Bonds', 'Cash'],
    datasets: [
      {
        data: [allocation.stocks, allocation.bonds, allocation.cash],
        backgroundColor: [CHART_PURPLE, CHART_SKY_BLUE, CHART_PINK],
        borderColor: DEEP_SPACE_BLUE,
        borderWidth: 2,
      },
    ],
  };

  const chartOptions = {
    responsive: true,
    plugins: {
      legend: {
        position: 'bottom',
        labels: {
          color: LIGHT_SLATE,
          padding: 20,
          font: {
            size: 14
          }
        }
      },
      tooltip: {
        backgroundColor: CORPORATE_NAVY,
        titleColor: LIGHT_SLATE,
        bodyColor: LIGHT_SLATE,
        borderColor: CYBER_TEAL,
        borderWidth: 1,
        callbacks: {
          label: function(context) {
            return `${context.label}: ${context.parsed}%`;
          }
        }
      }
    }
  };

  const downloadBlueprint = async () => {
    setIsDownloading(true);
    
    try {
      const doc = new jsPDF();
      
      // Set colors and fonts
      doc.setTextColor(10, 25, 47); // DEEP_SPACE_BLUE equivalent
      
      // Title
      doc.setFontSize(20);
      doc.text('Your Investment Blueprint', 20, 30);
      
      // Subtitle
      doc.setFontSize(12);
      doc.text('Generated by Skyran WealthWise Learning Platform', 20, 40);
      
      // Profile section
      doc.setFontSize(16);
      doc.text('Investor Profile', 20, 60);
      doc.setFontSize(12);
      doc.text(`Profile Type: ${investorProfile || 'Moderate'} Investor`, 30, 75);
      
      // Allocation
      doc.text('Recommended Asset Allocation:', 30, 90);
      doc.text(`• Stocks: ${allocation.stocks}%`, 40, 105);
      doc.text(`• Bonds: ${allocation.bonds}%`, 40, 115);
      doc.text(`• Cash: ${allocation.cash}%`, 40, 125);
      
      // Monthly savings
      if (userData.monthlySavings) {
        doc.text(`Monthly Investment Capacity: LKR ${userData.monthlySavings.toLocaleString()}`, 30, 140);
      }
      
      // IPS section
      if (ipsText) {
        doc.setFontSize(16);
        doc.text('Investment Policy Statement', 20, 160);
        doc.setFontSize(10);
        
        // Split IPS text into lines that fit the page
        const splitText = doc.splitTextToSize(ipsText, 170);
        doc.text(splitText, 20, 175);
      }
      
      // Footer
      doc.setFontSize(8);
      doc.text('This document was generated as part of your financial education journey.', 20, 280);
      doc.text('Please consult with a qualified financial advisor before making investment decisions.', 20, 285);
      
      doc.save('my-investment-blueprint.pdf');
    } catch (error) {
      console.error('Error generating PDF:', error);
    } finally {
      setIsDownloading(false);
    }
  };

  const finishLearning = () => {
    onComplete();
    navigate('/dashboard');
  };

  return (
    <div>
      {/* Congratulations Header */}
      <div className="text-center mb-8">
        <div className="mb-6">
          <FaTrophy className="text-8xl mx-auto mb-4" style={{ color: LUMINOUS_ACCENT }} />
          <h2 className="text-4xl font-bold mb-4" style={{ color: LUMINOUS_ACCENT }}>
            Congratulations!
          </h2>
          <h3 className="text-2xl font-bold mb-4" style={{ color: CYBER_TEAL }}>
            Your Financial Blueprint is Ready
          </h3>
          <p className="text-lg" style={{ color: LIGHT_SLATE }}>
            You've completed your journey from financial novice to informed investor. 
            Here's your personalized investment plan.
          </p>
        </div>
      </div>

      {/* Summary Dashboard */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-8">
        {/* Your Profile */}
        <div
          className="p-6 rounded-lg"
          style={{ backgroundColor: DEEP_SPACE_BLUE }}
        >
          <div className="flex items-center mb-4">
            <FaChartPie className="text-2xl mr-3" style={{ color: CYBER_TEAL }} />
            <h4 className="text-xl font-semibold" style={{ color: CYBER_TEAL }}>
              Your Investor Profile
            </h4>
          </div>
          
          <div className="text-center mb-4">
            <div
              className="inline-block px-4 py-2 rounded-full text-lg font-bold"
              style={{
                backgroundColor: `${CYBER_TEAL}20`,
                color: CYBER_TEAL,
                border: `2px solid ${CYBER_TEAL}`
              }}
            >
              {investorProfile || 'Moderate'} Investor
            </div>
          </div>

          <div className="max-w-sm mx-auto">
            <Pie data={chartData} options={chartOptions} />
          </div>
        </div>

        {/* Key Metrics */}
        <div
          className="p-6 rounded-lg"
          style={{ backgroundColor: DEEP_SPACE_BLUE }}
        >
          <h4 className="text-xl font-semibold mb-6" style={{ color: CYBER_TEAL }}>
            Your Financial Summary
          </h4>
          
          <div className="space-y-4">
            {userData.monthlySavings && (
              <div className="flex justify-between items-center">
                <span style={{ color: LIGHT_SLATE }}>Monthly Investment Capacity:</span>
                <span className="font-bold" style={{ color: VIBRANT_GREEN }}>
                  LKR {userData.monthlySavings.toLocaleString()}
                </span>
              </div>
            )}
            
            {userData.savingsRate && (
              <div className="flex justify-between items-center">
                <span style={{ color: LIGHT_SLATE }}>Savings Rate:</span>
                <span className="font-bold" style={{ color: VIBRANT_GREEN }}>
                  {userData.savingsRate.toFixed(1)}%
                </span>
              </div>
            )}
            
            {userData.goals && userData.goals.length > 0 && (
              <div>
                <span style={{ color: LIGHT_SLATE }}>Primary Goal:</span>
                <div className="mt-2">
                  {userData.goals.slice(0, 2).map((goal, index) => (
                    <div key={index} className="text-sm mb-1">
                      <span className="font-medium" style={{ color: CYBER_TEAL }}>
                        {goal.name}
                      </span>
                      {goal.targetAmount && (
                        <span style={{ color: MID_SLATE }}>
                          {' '}• LKR {goal.targetAmount}
                        </span>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            )}
            
            <div className="pt-4 border-t" style={{ borderColor: MID_SLATE }}>
              <div className="text-center">
                <div className="text-2xl font-bold" style={{ color: LUMINOUS_ACCENT }}>
                  4/4
                </div>
                <div className="text-sm" style={{ color: MID_SLATE }}>
                  Modules Completed
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Investment Policy Statement */}
      {ipsText && (
        <div
          className="p-6 rounded-lg mb-8"
          style={{ backgroundColor: DEEP_SPACE_BLUE }}
        >
          <div className="flex items-center mb-4">
            <FaFileAlt className="text-2xl mr-3" style={{ color: CYBER_TEAL }} />
            <h4 className="text-xl font-semibold" style={{ color: CYBER_TEAL }}>
              Your Investment Policy Statement
            </h4>
          </div>
          
          <div
            className="p-4 rounded-lg font-mono text-sm whitespace-pre-line"
            style={{
              backgroundColor: CORPORATE_NAVY,
              color: LIGHT_SLATE,
              maxHeight: '300px',
              overflowY: 'auto'
            }}
          >
            {ipsText}
          </div>
        </div>
      )}

      {/* Action Buttons */}
      <div className="flex flex-col sm:flex-row gap-4 justify-center">
        <button
          onClick={downloadBlueprint}
          disabled={isDownloading}
          className="px-8 py-4 rounded-lg font-bold text-lg transition-all duration-200 hover:scale-105 disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center space-x-3"
          style={{
            backgroundColor: CYBER_TEAL,
            color: DEEP_SPACE_BLUE,
            boxShadow: `0 4px 14px 0 ${CYBER_TEAL}40`
          }}
        >
          <FaDownload />
          <span>{isDownloading ? 'Generating PDF...' : 'Download My Blueprint (PDF)'}</span>
        </button>

        <button
          onClick={finishLearning}
          className="px-8 py-4 rounded-lg font-bold text-lg transition-all duration-200 hover:scale-105 flex items-center justify-center space-x-3"
          style={{
            backgroundColor: VIBRANT_GREEN,
            color: DEEP_SPACE_BLUE
          }}
        >
          <FaHome />
          <span>Finish Learning</span>
        </button>
      </div>

      {/* Next Steps */}
      <div
        className="mt-8 p-6 rounded-lg text-center"
        style={{ backgroundColor: `${LUMINOUS_ACCENT}10`, border: `2px solid ${LUMINOUS_ACCENT}` }}
      >
        <h5 className="text-lg font-semibold mb-2" style={{ color: LUMINOUS_ACCENT }}>
          🎯 What's Next?
        </h5>
        <p style={{ color: LIGHT_SLATE }}>
          Now that you have your blueprint, consider consulting with a financial advisor to implement your plan. 
          Remember to review and rebalance your portfolio regularly!
        </p>
      </div>
    </div>
  );
};

export default CapstoneSummary;
